apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - name: tic-tac-toe
        image: 015564824262.dkr.ecr.ap-south-2.amazonaws.com/tic-tac-toe:88dda0349e66cf335a3be17ff21bd18e52e9c1d6
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: ecr-regcred
